apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-telegram
  namespace: agents
spec:
  encryptedData:
    TELEGRAM_ALLOWED_USERS: AgB1PC1w1u446VOxyj22Jh+T7wx63CskP5znnx2cKY4NfvMjaFmJs4hGMU7MNueFRpfCzC+tlOfGhKrHALsnJkjoax6KiiaSkC6+ssoprtK2q4gpFKgomzjU52PC+2Jqz9A82EUUEKk2mmDg9dv57aLPrEHR0r9V575FBI9z/NIz2kgylfd+uunZ8FHDgiMvzg5yVDo1RbN/MgDK2wPl/WGRD7F9wfgt6nV6jGSv7x2GkpbTMt0IkVvrfNftlYMRWcePlo1L1+Q102728dCT4h/ly72a27Dxrs0/1AXhcoW4DJk7/RLMrmJ7YTHzgkbJG8ZThJqrkHua89jOYj6aH+tNhOhDEbvEVJGcEQiwUxkx1fT/thDvIBk4MNmdkNSVFh02+wsc/3NYnJsighzk6w9LYdicFri7l0P6fYPgiHgy+dK09h6EMRwLFOIQ4Jsd6TlrSm1ClbVNqLn4L/AgpEKPS6YQvN+T/9HmCq4xNIf5fjWBt4dwq5Zg9IetctD/SYv1gMdx0PLVu6tdiQpfH5Npssp9lDxkPH8Q8/y3dg0tjeWyPT8DvZgYIE3rN7mAO3rhKSRwJV7FD6P0BsRS2N8Sdgbg4HBaSwpxtjFBXk03QNKIlyQDF6rBgIUZWbn/Alnj1q2zLgYl9PsY905fNxRJR9zsDurn7ENvRZHG27pCe1y8VDkbGiei5smlaCtQ2sB2aTAGKwurcXs=
    TELEGRAM_BOT_TOKEN: AgCGzyBMCf5Ka3sZhLoY8LP973H7QT9ulaUnfF92EbzmsT6lysfrr/IhZXi1xgmgqHxHB9VCou2TPynRqoz1ScKshGkTND8d+PwMCfMlPk7zOW81peSVYxku4Hk0C+MFStkbHqEF/K/wgiAI2WiFDfIebYym0r+TfLODzMxR76AoSLxWWyAIH/mtKaBQALOU8XFxgRq84pgpIflZN/PDPgl6qjJeIwyJFGA1mF2HdxXbCIJtGPk/q509SyCoRLSp3We00Jmfbrtx67PNP8CCPehZyhsdYuhQbPHs9vM+GT1ncSqlCarVk+trFgq8FCzPfm0h2ACDqxRubIQlSg1ThcWaobWJ+lBM7i7mgaIXm2CTZjoelWJsV/66FEM+x+5AuvzsmBFH/PLjNlHc8mh41nSaTzvMr/OtExnqY18oEeznjPRoWRWu7tvpm1PgrGofQO8hWVd9m4Djm2fPefo8apJfSVY4kPLkkt2jn9Uq+PL1M4mcFtvRQCuGSHaCU1VvySjVK3dVSEPvKVjhH+8Y8tDyyxFk+uOCJj8fBAOC69F9u9ANgdKvquB8T8+aF+jcby4VkmIixXJPnvKzznIqwUAP/MyWGTA4aS+3x6z0cbeml9Qo63FjKitd/8M7dBIYQuLkIg8TU4HMnqJIDvAnlPV5SPuBa3c7HbVElR8umy8x5gK5spRu/lopuc0LFWX4ZxjTRDP5a0WBXcpwlfRNR87IqrU+C9piVF9zGYM9Y9qY7z5wjoXQL1DPYl2LusW7
  template:
    metadata:
      name: hermes-telegram
      namespace: agents
    type: Opaque
