apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alerts-telegram
  namespace: outegro
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgC3L4QiiaT0T52WeOFH2k6ohK5Obd2mLG5MV4pG3UcBABwWsOmrSGpfBKXfHXqV8YzI+KeknPirDNOBKuYifVnnNIjg7wL/k4tyBFOgAMHpBmpPRROx5CGu4xrFxB+xibKmrm9r3DlRB002DA9gQZPg5vAYKaDksOUdi3JtnQEr7xjtBFd9S3lEMBuLP4121Yco1N2V999U0d6PKuYVGCpsk1hEMoUSXVfsqiPva2j3Qe5WlU2o46+4JyfpVUUCILPSCRHhUqNeOt1LJEzy52+48vjC9ur+6bt/gkmxZto/joeqwMCOrUpkR+W6yBYyydWL29uR0gSSGWfByvbgXY5aBbBdbISoqve4Gp1ZGWfpjdUdo+2tr//cvAC97hlQ2mCANPWLehnky1n/frK6TDxeXPeAUNfOLXA5cxGk/1b3IVotsEnePdLOoCGVirVDPu7TTgqzF90p0/i/jvFO77rmaDwCRArSfKninyrTYMlu/uqIOjUDKbHey8QFFkwuGWMI95hI1as4sdN8P2I8+Vb8LMMNfhZOmrPukraIlFA0uydFsXrmfRsEjANhaRkIfHndpyj3GqR/hzxOa5e+/ZT1w5mNjtRHKracBZgaQpPTlQtGMQdGS5n1YvFQffG8f0KEETpeRAnKNWRptjZIK97EHyzMNw9QAxCqVjiSjb/602qGoMul8yYhY+1u6loXrgP4tR4dX55ABIaUveVysC4TkzokLG0gd5I72zRLMQYd6xRqDuQgIYC//gD3aKt7
    TELEGRAM_CHAT_ID: AgBTATJWBlDn1jWDcK54VbfbC2Z2eNpSD2ofL3RHBI8lZNpjqiluppEoHAIvLXEtepXKxWifmMAeMZlNPrK701lSv/hb5myq4q9KFUmFvH30AJZIOsWR6o/4t/gEWo+BlMmQyci84ctcsnpWYv6910UyV4tPhvkAFJapG7i7ns47dRY3rR4uYEBtelOpQsEyV0p9ty7y6KveWoOzQVhE2oR2k8aaErVQi9eFz6wBEVqEcZOvKrtLqeke3dlm3cGbnGkzD2Ko/avkA5Gbv7wbHFkktyE1G6aKjDell9ASYFEsVxBnBTLPeysl4XPnoaR8UGJmC14RdCDdOjDHtLN6LOHC/JRN5b7DqDV76/rDBs2Lgfng0/YLk4g4dlxQKE6s7ttYxdrXAiHbKUzdWD+ctDI4IuSh9lrl0OlDAgTi5o+B/pfRQFHpVtZoH3ES+t99C/0B/hhA9PGj/35ltFJLp0yF6Kxf+Kyi53XX39Y2WMxjgEdRA0c+WB65FVI/9ZJcuYcVroxVpTQSi7IAdiXftsE1c+JxrjOw88bs9fhds6LPHLJbcltu/M8movnMu+QVVfdLP7mAdqHGrVTNQq3Fa41Vhu8UjK++vF42/KfJ3Kq9X1c06JkYK2Wo1+BsHqXVW1M6uU3tXYVnOdPnlgcvcretGoGyS4BiBOo0mXdKbALqfC3PdZmx8B3D3G/qj0olvYOJS5VIa9MCZ2A=
  template:
    metadata:
      name: alerts-telegram
      namespace: outegro
    type: Opaque
