---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edu-assist
  namespace: outegro
spec:
  encryptedData:
    MINIMAX_API_KEY: AgDHcpABmpLW7uAh8R/rw01P+d0voG1wmDM3LEEyCj+onSHG25nCyLnJJvLPX5HAWKE9KY/xCaw/ehf6zwfGgiQnQZEDPgph93jq5uCu6VWgkzpZW3paBVokaG+qWq6YjMvcI/OyGHv95KKojweVETMMCRldTRcwEUJXf555Z8MMzndC0/3+hoNJxQSl5NAsVc2NXnEzK88YIljdiXcsQeYhlrhQli2uDg7FzyayTowrxafR4EO1uacm/AbXQYaiUduCYBbi8Eq1lccX3Pbq89h48/3ICoEWOOv86sd6ZaSZdAEGNolmbkDXB8Tuuts9hRrf+airYJVf/Ui+MFvQvmr+33cJWw16KB0fhnYMEXADks2HrSRO58BzCaxQBQ9KpkSWORXeBWe5Gnrc/QzkITOW76/TAngG1vfNmqR+x+5DQcpesCaNNl50Qli4MXWyHXQXxUv5jcSdfuEkHGSAKUY/Z8+e+R0YBYI+3rULB00k9IzzV6XnSA2EJ0g+A7qcVH71QoOaF0uRJ1gAVVxEgeaqcjCO3xGVZEI5fuBqKHF5UqL19Gxmo+6wpm28XdYuJbAWzyo7hXN4uoRpOkSmYzklHMrnWfNk4axqZ3lYYNQIKeG/gZkNS6byfX1zeQVEd28sYllWuV+mwfhJuqPfZj0smSBvV/i6+nEg7zow1pXH9SZ43wVAKLW9GqIZryojD/IxYpRmpryIzx57NILOFM5bm0Acy7T53d4KL0tBHrMdlnuohV5HetlNBg2F/PebM8azQ0ISABgCgpmuburySYnkLYSrlO1vEyECcdXi/q7PCiR/Z5iT+2IyuZariVgBuz/NyEyHNpNVqgOhz3FMkzACG4nyCqbDn9b2yhmGHw==
  template:
    metadata:
      name: edu-assist
      namespace: outegro
    type: Opaque
