apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: outegro
spec:
  encryptedData:
    .dockerconfigjson: AgAlXTTQuJjba3T5eUreN3+TPcSOpD31qlbFkhtFfN23ajD6iSbtu7NVMv+0s9BEx9yJLJrhVahXL0bJQT77DsDC2KRdD8lVcWIOiV53QHOq2JV9WAvrK8ypWW78Owxpc554pd2ZqJ4fWe4cW9fVGwgRjPSAcLR8K5IdfeWFjvnL8LLdbIf/oL3P9HvCP6SvahpPZQgL1UXUqpQfDUQA2uD26DJViut0lLfybHuvdCrxFsvY2obFerI5/Fea1/Pt7LQ96poSiAehN6GNR6a9zKzY37dYFSr2RDWuAQTlcrdn9ZYJH7du511QsndJqdd9gJLf3sKi8Bvu7W+yuNR9+YJBnmPUwYeHqPgayVht7r9JQPPzcpij61cGPP28gXc3siaVk45cPYzb0ZTtU112Nq4o1UixiC3+dX8DT9qQF6YVIcf6Sps6HRvvvcUXVqKPb323EKBuTGCE3ToF1DjPuKGGP6vXOVWscnq0dAHQS1a6yWulpxurfIx9OlIlOPEpATaNySKzdRbiLb700UT2zZ96tW1EgqixEmOa/fKiPAVhIldGYBm58mu5V70e8MY8sD9zZzOrVTNCQf6wweoljs/3Y3mj0MFi7UkPdVDH7aGnvaoXzFYMstaoBwVlxfottoHx2/PZPDfG3LK5HDrSxCAfP+b+Oh5BrjvjO+MllPXJqCXjGrq9otX38cb50WfKMWlaMHankrDKiX++LCzVcKwshaGAEmKLenQJtc1DWTp1kdR2DXOl3wWfNEFQEs830L2D+AmoQ6MfRK6jzvUbs50Azgr/Iz5o23BF4MeYrHie+rU3w6RmS2eqkb0+k8zYXAvUEOQSBagHEBwWhfBZ2FxPPvYV8Gq/IvHV9FTti+ks9nFiYXUtR/QTAWH2FO9UJHIXfrO8H+VCsIxjpiGPrE/63IVBZPAMfV07vpcL4dYkrXhDeXTco04rTp8=
  template:
    metadata:
      name: ghcr-pull
      namespace: outegro
    type: kubernetes.io/dockerconfigjson
