apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lava-webhook
  namespace: outegro
spec:
  encryptedData:
    LAVA_WEBHOOK_SECRET: AgA4tX0TrTdZuHRe0/QcXGQeJE8Bc1NCVDzzxcUQo5SonuN3/WD8Wz3ZL/z9oj9Mzc0bd7sNpMzrooY+rwQwLoBnI/cKU9nYN67/WRlEviVsVfro6YDa3LmfGSjkdoqQwQSEcY1YSuaoOvYmzxcKDdgA9SuL14d82/DYLP9BzKc6jNo2t6le4yJL7s7DpGs2L8LNosU+fFBwMtjLsgWrE4KB0NA+2xUWMVRbiJi/MmBBqWYUZsDzW8F26GUx49z10J1dsuFmjkiVsoBgX8lJxXAw0MAGalAcsFnFfOVFYVnIfqs39YXE1HGntoz68eyAGQV3BGVD8A6CM7A7quu7gZJSnuQFsGhV6+Fm+QEXwcejeEc54o908ehpYR7wenxh5cpN8aTnh2HVf5mOQyAGa6R5UnkgjhfgsyynI9FKxkDr5RQMDKXI/AwYuTZDdXfvKCSB1zlobP8uhHH9/ELtNv8Fmu94th8Rxdq4Ca9bBpgatXUE9ekpwOhGvfzFmLoQHPv+tl2D5Szq0W2sFiEu6TDvtSgso9usp/S/KP67BAEbdP1hVxyKUTZLzVAuy9h6o9J86BC8R6nBwjCJyo58vXNibp8Q6hzkGymKNrZDVZ1KCPLUZPD2bI0ndI5NhcbXZ+rAf3IEfUkXzbVvNGR3Sv6d4d3dXUQlPVmqCLqfjtF0WuWTpjMFRkrQVIoeEElim9jUBA+m+fMww/2Vg8IIJlyyHDwCqG1nNdoj8QSmEB6ot7G5aTZxJhpYGCxB8eUa6HI=
  template:
    metadata:
      name: lava-webhook
      namespace: outegro
    type: Opaque
