apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lava
  namespace: outegro
spec:
  encryptedData:
    LAVA_API_KEY: AgDCXGKHEmisrirAVTuDW46vWajEkFtfYIETmMXLdFy01LswPBzPo6cQfcpO6sJL6SnGsq6m0lXAKI4F7KqronjEYmuMCxnjYSWeF5CONaB8y4hx5QEr1wanBBcnMm7UPkvnIZfuszqcuATA4/J9JgJJ2f1x8J3fVMEulZT6jvSwr+d0Aduv814/5HWUB2PGroXTrQHiNdsLhXd/7b7gditZF3FEuom9/0/WRzx0WDwwOuKLkgWRgPgvz2oI63krDy6WVRiPrjZe+zAKuvPoj3Kvn91UmC6T5S6/4xFVSE7B7D6SpMPOgGDATKkrg0Xv3f11EHk7EqyXySOI/UYV/eUlNNvI0jLjFob1EWQd7R5MQjkv5cNmgitkK0lVNsOBhBv7TRLjFtbm107V+StPxI3Tlr1ivRpy1ESUdyxAFFLwtcPN3qFFI0TkJbYXJbFikYj7YXevVN7s/C7Y4AMbb2sGYbNqU6o5P0+u0tCeoHcbzh53keB17y+a9A8e5jLiJhiCAPzkKPbkgnvBpxDUtz3ufF2Dgy8RJKt0X+2qDZjBCvMdJUaWakj7EwZpHMBd19M9s1XSOMPB7Tkup3Ijll0H8BGCcv24mFQFlQKQEFRhG5FwsHBG31tZdTVSL0hvF1/d/W2Z24ZCfhiWNdI9Irfm3qeEzd1iSdd/cA2cxmoF6l8nx347ZEqoloVavh1Ccs7dBvdKyGHV6jqcQWILZhsMk9dl6vXhDyN8GUh3Bd8TgpPytKiFmvoslcwcQnJTQcVRCh8eFAXwmfkqD08SIc1A
  template:
    metadata:
      name: lava
      namespace: outegro
    type: Opaque
