apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-auth
  namespace: outegro
spec:
  encryptedData:
    password: AgDLyfqitRhaQsCwO6rOtOu5iPKxc3Xmuq7hDQNrGMUNbzHYaw92vgJl3nSxra5t1X1ZAmW1R67tYQMTb1UsMTz4LnZEEndM/AfcaRYIEchNV/fjI4OoF72d0TS4xsNRhfNtKsWhRnc3Hm08tLTOP6sffkrmQIDPBn3ML/4cZ6tuZcoJcY8ZbkbZ3Dxmcvp3tbSRP8RMm4wSpUrzFkcWd6l8bHOOoTu/3rWbEvHARKuXhTarKGS4siERhEztMQprOLq6TX5chr7GVL3kuTFiLT4wHaCiMh6MQRZj+a+FykT2LpCEFW2/DpzpHu5BdVAuoxfYIpEO0+A3Ltv2HenibQOb9hjqaEB/nc+qmFqlWVruAWW+7MrQRSQOsxff8pM207mHEisXqXhmYDcW4L6lv8miSNZARqoRG5+Jj0lOinVj0Y2aDVmW9J6OH7OPghRjl/82/TCxJNHsNvKGrq0G4Hw6qroHDYZUVofJuxfLAz/eslj/oHNZHFOUAeuhBOpBEgMl49APxgV8koMPH4WyZd9akhZzxZ+xIv2/oNBkt53aidcmyfuYelzm+dHSFeQeKJeQ3y+px0DnX4Isl3MrfyYPFyD9t94FkduumAJS2CIWwXlW0Xe4wJIvDh9z/P+ZmB8TjDp+OlRTvJYAq8DaXzLQ+zeWMWDSzTHQ5OKJytse+dR37ct8vBny1MpWIt963uezol78pvSMWxZrWUzP2BS0pqVOpqsx6Zkbn6MMSI23MFuEVrSpw4sylLtwHbFGmDY=
    username: AgAIKXB2dvUCnzcKm4N7HupYHCSvX3poqBpz7sTRiBG24PHgcMoip6JgSjvX6XzMB7i7wzpmoVkMclf/13fAeD2vh3bPEahnszgxxUNwz1nkoghf1VWADbvZNc19wCMk9jd4QhTQDcpmhrPmO07toCLOzRYUz2P4wNBP6I01W12tIm6YzKFsynJK9y63+CaoNgWrcVwyCHe3rM15VMY48GuqasiSwtB60rtAUvmdJDFNnhXCWdReum5itvlVI9pI8waTNSiOu+Wi0kjKknToW3f/mTgIlnKEGhRPvA2OsHfa0uU0Z0692jyeoTTYiagkhVIYOs8PPUIvQAVw7JYaT3sj+v3Tx/h8vHAqAZ2lwwSP9IUhPUi5sA+B7kN0msgvGD8Df6YwT4b0jCF06xZpt+hP22frjBkACrUzBxD65dEkxDSxiiNP5q0bUpUgIoVlfnDlPY0kW3sTB7XoDhq35d19VGkH2ALjfPNW0zTBgrDmstjSORR9B18ZQXl1UwbwTZaJmrWYma7kOFaP6hc0Ia3+jNHBmPEG53oak8L/Y1bc0TU8QvfMyNchFnYp2hzI5RF1eC7IzzrA1evFlrpUEU/LiVsB2U/J5RrAvsi8pga1snyKtyj0jQCcl05SPlL/kX6Oja7x9p5haasBnqp695j13+Zm7PaGWyfGgU+VwsLi/I39Y4Omgzfqk6HefG0v/CWq2IQl
  template:
    metadata:
      name: pg-auth
      namespace: outegro
    type: kubernetes.io/basic-auth
