apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-battleship
  namespace: outegro
spec:
  encryptedData:
    password: AgAuJS7FkYOHfVTUwZhO2W2K+4yug6teDdaZMVa+FEjZVgLdb+kM09ukH8/BU41BGHPHemAPVlZ68kYhKKkSJYI8Uv1pUv3by9/78Nsqpm8A7iNZd2D6qSzkoiu5e2LHNfWufinSyqZCniZDznvvy2g/TEyFsFk+9Fy1smecUNNJW0T1DQ5DM1xm/0zvEu6j+ynsm4Ix5Xq2jPelvlBbPAjYUQD8XBLisVGUhOZInsTVaRPfYU0YLSeeykq/wmPzkwYUOu9P9X6ovbU8E0NmvamwfgdPv67Emnco2JHC2X2dGw2IlkM/8dB+zUw3xKVOIYO2HJhfnuORZ7H+0iUuLy7Ih6JupscYGvPJeg7g0GqxsrmE8KnEAXWSFHcOHRsggUMEmGwrOg4k8ptwFXLRx1rDFGWwuI1LuJT7XP4/NGvPDqOdYYYEvI8F0imD6Xn6AsTb2diz9iGsrSPd3JW6VtcVeSuhZyk5XSlpg0Rv7HHuXwCCLwMiNDgc2qcdbLUNs4STD/bE08xRMKPn8hm7BQAI2OMiGJTaOCqcfUyJLZfhc8Jgngg++paVP8aBgNs6IxHjwsFqqikMCoeK325lc/zj8+sUBYJZAhbiI3p5wBtcm097Bf3W9ghLLtY9B2UMBrnzdTFHWAMsbGZvBZ+UDJMkm7vLiBeYN4LYqyaXBj8wbTPImfaAbD3rUnbZFoxMX79hbcQ4/25Mr7V9mbvGa1s5kaC2YqZVfV4jAtLD73t1fJ7ouGXMixnP6EZdND3n8dQ=
    username: AgDKcJHXSFg9hIJRKUhlBRzl8lp6vWT/7P7R9lPHcOuKzI6uWZheZZCN2WCCmOIJRYielDgpLLYgdEIm3fEWwf6msLoPMtincZ7YZ8sYEqVbJSpPXihBFMlcpqz19ORAZ3bxQIIFjOBkPrqZJ1cMZwAd4+RDseLpmAYxVEKuaW0BmOQZAuQjx/3t99cZR3uk2YdBIifnJdhrLKW9ocmMbK8V+sGUQ0EkTQVZmhkNihefG/MpMnjTB8lnvQKqbGRppTL0/399ybyHNOGFAntGxwtucPVeTFJ8Yh5uYlOfSs1RxK4CV0crpjLQXt7Jta3Ru0LI1WyEM71WfjViqUN9hjJ5wqkW6tUleLjgl1fvgvXx41xATHphZ6XVJjzrXb9fDo1yo5sWkKx7CRXYzbG/IXYN7D4IWhVhr/TU20pvZhrM2UqkQktVBMCi8Bph/QxTukE8FlPMI/H44BpyAas0p1OKq9GXRaDhWFUj1VNgsKp2mAvHAvrWFElJuuzEqDIJVGptt/5dAHxqxHN9YWYjSCbw44VgCzXF4mYMwvT40xhYa7MTtPwNZf/4EkDavY/LVUIhQ5PwTXVBkPbmKLQuU8Qqwg6x4QOL1q8JqWH5XpYJJXOSppRskiUYgmDLz01JXCfq/eNlB3U+Rja7Xh/27szYzrHe81MkbKThD83u2s5R4GgEwPzMMZ07mTCrK6gqbzy+S07/HysBQPdc
  template:
    metadata:
      name: pg-battleship
      namespace: outegro
    type: kubernetes.io/basic-auth
