---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-edu
  namespace: outegro
spec:
  encryptedData:
    password: AgCbwwxiWPy7p6ZhKpFRqbFsM74LF3VdUFBAxL5U2y85q7ARHb52fCkGAX7k1fx9ycPZp0xYCt6MVNXtiz1rw3IfUwPDkC6DTZzyFEvg7stVyWksH5HRW0emCvsXJcBrbPAUQB8+r8Ze+iMj66Kdz68EvfzxxDFdjavRkmAWzQaRNwRdSkOj5qdhfPrzXJXRy1WIa3mcKIL04TFt8PgZHwyHhoZxShpmKZPo/Wl13Wsc8wqW38g4jzL99Kc08E+w7KPiwhM/nqTZX8VFeyBwrx9Ik6dMGf4Ih0wDMxMaereinttYYoxNV1uEbR71WwcstpbwSCgaW97seVl+tPH1508A3NQBgPwkfHRodFF21IbcjmnCmk4VUqORCD4bMTI5JvhXQQU/d8xmvsUTAygiHeOzIbPzxATbBE3ObdG/d9tijA3ffyHJkLIMLW9n5RXrCsWiwJbay2foJUMZgy63uYogz9FH/HXukDG3ZCAbo8PQdIRi79pJMTidrB3sUUOPU5TOnXvUWlW+s6LeGJeuoJNYrVf+PX7ZJYupwq2N2SfkDyKqityJ1+4CpI4pxWql/0rnMDo4CRjYpzSdPHPvSh5jbz9eVWpk3AwdUKJDueBVCN9Hd88TI+nFmGqR8bvXFDunAZkkCjF1F6v9utZoFmEzHLNQREEDfczcruGGYtJW3p7GC188c0i6OhOGlzVEwpN8nYpUeKpYnTSXNTM5EOMemzwBxrTZS4T8RQHe3hp6/w0ggxllHegNdYcGtff2OIE=
    username: AgCAwb6WGxOij9yhg1waOgRYR+V/bPNtHf6Z8TTP3Dw/wojeiytkqYA/L98Jpj+bKffOhSvJhDgJbt3BP+GnU0vXiywEDC2Qz9MLKtsmW2SKHjoBYhWGfuWtObryrYOD3h1XkIJy8PKfJeRrtLdQQ7vXzfJAqiqayDX464Jy+GrvuakpXJUYgLPVXDHv+1X9qjgC5IE7PPLoXke0T1HjZcKiAZV32iXtmEwHScFktkOlWHOvWHbJAtXjY9hnJ0vywujQMjeAPBkxFEyEXTuBS3efKMtSSsmGM862Sp208IgH1Qh3UzKrvruNDEQMCooojCgREqtLwvDii8t1NaUYLCATspvx90Q2LGsVzmwlDDOdIc1DU1YWmeTrQTqRkXJFYLp+QqtCqqk4H4zPAsHED/8Cr4dRCoUx71SKVJ03saZOPhqBR9bRgFncxmLynGwFMLJy/k9Bmdc/2Aql5s0NtLMR/HCwUfOP6Uxdxpn+X+xrCe1hndAdeL/QfS6omImq4fk5dOiSQ6yIbFRHyVypcOndiJ7ate/n3WjsINQhr2AC2SpPy2yXhdx7tTB82vdKMwhqfpaCa/72rMikJGgRxuh8fYlAmhm0cY7yb5cEDh5P2FhzpXAZzUWRr4vkTpFlGZqvH8wBQmdlgu+jJybevJoshHxomTzA2PEKdSU5IiPtTK//sse4EE1wS5ulnr9qd3UAfz4=
  template:
    metadata:
      name: pg-edu
      namespace: outegro
    type: kubernetes.io/basic-auth
