apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-notifications
  namespace: outegro
spec:
  encryptedData:
    password: AgC00ujrge8rgOueZJF63SrggDSVWcNMGURPjNhWnBXpBEXYkUj/j7uan98w7bZPPNj9Jjb72vdBVWSDLYaJosxp6JsgHbbMYdCtXkkQwOuG1Hv/7ENQcF0wtzXJtpNHvi/3hTvups5ChfvmCOF+HwZYyS5CyAFZ0V5FQq52fNEnDc+10LsNzTJHWaJSBmk3DQzwlFwIkd566obej21L3WKDsdQO1wwx6fazZ9qgRFt9psE0Q9q5765eyXbb0XgFqd3L5oonY7ZAtZvgeknsvBIh9GOkd6n1U/khzSgElBNT23o/dYLeuNy2qly1gMfqw1TWboGj1Yds7JcMmqiqqwH8VMKjJyMoIRg4hUDbjdEvGUkRI0IlQEaQ6VIFEx9t2YgeZVp2QvsavAxqxeEsUk6/doTG+64lgFR+6ii4MTR4Ky97cWlNrXswKyB4WfwiyW4qMxKBdp/8WN7rV3yW+vKCqd+uVdTPA8b5YmmCm+X1YPZPNNjGeLuQvytx7ITERIHVkCHAkLZvGkwR69aD8meamJemWvi0N3u1ZFcZVxGiDoscQ0UI5oc6s+UAF8CnrxuolywJZP44NF3ha/ZAPa+5n12dg/aEEyMhkFV4Aca3wEv3NvnN2QncOyO10GJoW5JSMkNAuEdilliJZ2H1MR0+kkIK4zrP3IAGsXAw+mHFoOjX69ku08xhJFrq7wjxZ8Ag8QBvRB4L0OadQatX3jo/lQXTVK6npNMn62DBAZrb4s/XtPLmyvSaYqUPHF54Bxg=
    username: AgCy0YboeGrcvZXnlt1CQSH1/j+LpGu/X44HOhdgHwEVn+LA73Es5xojhD9cwK9qEJs/Fkm0+neuNJdMUzroOFN/k5XDUFCtn+hprmUToNDZWDOHVVSkV9GfNUNFGf/vLTAJrBU3jbX/26sfcidrUiVsLyUCw9nYHNuJffFuRjbJShSjdHz9CgMfh4erCtreVamK6kRrRVruIXWjxdfDeRlc9cWS1a41n+zCrHCXcaTFQDVSYMCUOpkGMUiHpFqSFrY3mpU8GWDir8XcLrqSphNhzsoob+HRzpmXxWZcJAPhbg6Vewh4lv62vfgdFKbrXkxOv9rd2/OPDm6o1RVxDKW6kzsH9XyFGvVOYzFDuVE05vxurmnyu9woxR1+sXmkiswGiy7giU/76f9rxLKyNesMTgNwz8dISJ4BI9LClKU51oVYBJmvIY+k0opY9HQK+yIDZ6I6GagOtPjwOO/KTZEARbA/IzOqp3WVRkFaK7KB1wtU6cXZ/WvujrwwLk1WrIOOrx+4z4jIHMuQUQdWQDoFXQMtE309INL2Oorh1j3XLLmDLVRCQGBDWI3gocFqJjzEZ3GIVZ+54P0N1/sELJYeti+kLoqdCfkOW7NYejhhXG5Bms1oWY6Jr5SIU5351baCuZmFjjnI2+pJQQ3pkxD1OXqlptORXmvjWo1YinZxxijc8KXnhQByoLhP/349VVUksUTEOj0/ay/WEeh1
  template:
    metadata:
      name: pg-notifications
      namespace: outegro
    type: kubernetes.io/basic-auth
