apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-payments
  namespace: outegro
spec:
  encryptedData:
    password: AgAN+wh6QbdeO8UNykrQkZQTs+THw83LC0xxs7deKIiPj06Jn+0Yf76uxhJkL9yyN1ffLsvjZdpFxu+X9YFWKRuB6roWTiKtEKRtJG4c3sx3ruEEmNXqp2rovBaCf87rT6/lzXrH8xVzI/CZ1ZFxMt5hZl6qBkKM+6k76CnsOnQwirSof6VyGB18meRBpc/iYsTIdmDNr9WJexZcnbAd2aufMtf2Tfz+FpvJsom+7BwLcDHtMonum6GiXAoFJkzVM5AvtOqdN4IMwDOTstO9E6KlFJZHTJ91RWu+94shESlStLb3YNhhhZVuYRMmg1GmOdhxL3J8CbBxOi4Sbs19j4Z367ZTZ5ei2aOD5WWyqCHMZLbKlGlnmoUDM3DnX5eIJu/plbG4c7X/PB6OdC4kQmGAmwRzkfHqYrSXG+1mq4z+44s9estEOipEd/9gs8GOm8Obw/XTSBnjEozhwfbtEab4jhxcmc9DM7YXSHHqlcP7hMAz0go9SELZhwnVEa8R/0UUwt2GOjqNaV4YLG1zKlCVpBQR8v3MUhU/R9oXRaSdtRsOruvOPvoY8vVINzeZ8ifiQrjPAr9ANrGuzGlizB5dwHmGCdTPeuTojxzpP3M4+TZGktF2PBHgAWDBNT/rqApf/YaBlVxnbimFLU+MDg+lbsUbvshCLJqo73AY7SudUzgXNNP2nJ1/elabIw4ezO3SM6jBvym3WKZzDR+ckqBw7BjV2Ljsfog1E8Rp9OU+mJ0vNsT6ozoAI+tCjdKpSXc=
    username: AgAeyRSmEBGiCyLDH7nMdCRXI3eO0ndweckYFuCHXTpMHZbyTwm3Jjv64Ijy+ro1qEADnfWbZPlX3HfB4vyZ5PD7Y04uEaQcBzm4Ai+v/KpHz6zJ3rn62Wx7gvPI3WZXQyt2rn1PatyfnWOE+QLArZPs/UqGlrprc4wqOApZ6CShLIbSrZExva2pO2ViDtkcB+VD3D5oIOU1B0AJX4D+mwlaQRMS8VXPQNz3C1CpyoNgBxvdhdEbgAP9+zJZLuFMijeZ+1qfdONTLGd1OGMzEo5U03xpLH8Ch6s46dvePL4xyQ1AgPbqhu9sk6OgTpNHAQ5HaptjHHi4KaH6tQ29cPP/QAzYILeYYpq/t+6UKD2/SPXiNYAn+UrVmq6LMVyckTm/Eop3i/WiqH15CMje0LN7JKypOlmicIOOgSvhxsFdF9bD+icsT83gFgK8izcox033OajLUqEd+3PgMWDrMgVJO9QTfs7DAnPGylKcFprIhjH0L3LpCzIEuYD8HCYsM1CYtnJ3qG0SIlzB+Bma6xb4a+viKHBfPRRGuKKOTD7PUuH24YRP9gjXr2pJaoJEzg7D64MJXX2G21UCle2yY4g6aCSjIkDmaOv2pyX2DEOTO8btje8ao4DyQ+zYmwy2e0Ld7vol7v0xXdJrkCWO/wx8xSu2myYc6SwSPtodweSMFDxcpuL0RsgzS4GRAor+P/G38IU4PfoGFA==
  template:
    metadata:
      name: pg-payments
      namespace: outegro
    type: kubernetes.io/basic-auth
