apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-internal
  namespace: outegro
spec:
  encryptedData:
    INTERNAL_API_TOKEN: AgA0xGZnot3W062X2axqzmuhsp3uz+DAb7Up+XSwemxnKaz1YLjiWDnsvAvoAkoKwXZJ1EyjxsgZ8ra7g5K6NtDYKcsJGrAzNomTr865AxOh1M424LDomna806MawpjuNhhMvoVHJkChSK1R2nKj8wuv6vxG0TV5/glimL9mFffP3eyGsYfw2FDcc089UuPqUgSIus//6bK4TFc4v2hQXW02pmil9/zpEus060wYQv01o1N0JayIZiDYO+OUwC5vd/iw49ZKr3qd/kplIi3QKISa73CjKIBaEwUzlNqTDmjjdw/Uk//DSB8LHekbpSyF28oV0KrUbzxy8IAAVB56SmXHQu6u0SYYj/ZghWnhcgqjdPoQ/CYn1RZ6TTFQCxOYWcgKmmRlmN7c8FtpAVIWglUXXX6k+bJt32Wxql2wHsNLCpYh2GNd/FlTPI82sqvPf9SlOhY2BRoVFhmM12Q0v+1L55fLyXO4l5/9wFlkaywpst+hG+08BB1latFBkxBuM/Dnn3SoVLrCddE5L18MiD+gdV/mIin2HeE0PBLTvffe25S/nciHjQ+jVRLiUn5yLsB5YSi5hE59kYrw6vkCbV6cAHosg4SMcGHJ/8U+BWrPaEnIS5o2WiEbeRxDGa99M/PkHeJJwDUK7hSARRcovXAASP5Lh4BMd94q7lUiU7vh+LA8LN6LtyNb9uGt1g+U0S91+o3gkoGoHIAny29SuWCLjBIkis0+j0z2ncZvmbBm5xCQ2pLGXw/1C+JAItk09eUfGrWAduuoLDYfCkyx13iL
  template:
    metadata:
      name: platform-internal
      namespace: outegro
    type: Opaque
