apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq
  namespace: outegro
spec:
  encryptedData:
    password: AgCrxybZzebGFSiJ3LgY6IAb/WAi0RUwgsQtr16L69UpmzxGWEUOMloOZaHjn2aAo0l/Jsikn4E6ifjZEzUgCzE7n8WRaG+bbyz+KO35xSAy39DtBkgsQFqJKdZNvJEm0vpDVRGOiAmkP4spTs/gI5v+OZtU8B2/rdMcjrCHHau+9yu55YKVG8ipKKlzf0NyXNm1TWPHFOaqbzgVcqBUksRR5Fg/2Fj4IwTuYFpLrJBO7kWtwSPScRIfgaBNPX1snnAeKOb1JbDPkfq4VTj6hoUdszsgooCu5keGmMAN4TkDWDDYOZqadqKeAEIwN/uRGG/OUtjIzAvjdtjBzO8RQAB9v6VtAM9gd2FitM9eV5tFzJ0fDoqqa0pfJWA+57upDplMCxXpUI+Yl2LiDNo7sA+AUt7u7SyW5L4ndT/PhNR+qa3cPMmQQvz045JCwjs+xIynjNC4qLJR5p7ad55fyb0RX0fbinVJTl+NC4R25cv896uoRgy0Gjqp12vaseKAdCDeiALC2TiRhCx5/bhLnea1+5UcV8XmLCdAUzDMXnYVACCDPtbenWodDmXinabeR1c1ZmvCaILP1vzue9++NXltzjs+DqCGwpcoQPKyq4ixPo2w/cuRB4fz4V2tH4JhYSA1ssP2kBtwNYxxJ8P85NLL4gGdUc7zH9W/URzmgtgwC26yYvbwhq067/eo/CMuHxIztD0GaRmTT2t6UMUMbV1lvAMmihxxbT3LjWjkmSiSZJV1/Am3lffma/E0xN/YdFzAt72gxTtFNdVNp1iHfzDB
    username: AgAip29XRXbzXO98UgJsq25GFZDgj2U1c8ewk8MPZPwxHGNdnqn1jclQL4JLwqGE7g5dRVtiSPWLxMLsyThOatZTP0n9/FNlU26LRaXetnzFtzqdTp3OYzK+CoZzLsKQ/3AuEy2tj2waUNHtK5AxB4BCMXFlmAz4kmG1CZVqJp+DAuD3vl15kfRfEGXnQY+2Pi95asUMKOhHJOa+Oic0bJutnRWTv4Wg44QK+JrlMOIwgb3zPaX0cO5NVPx+av62M4Z9aZqxZ2OqR3VPl4Cb357Gj5Dbx+fvRN9vh0sjlut9jMzJcyE/2/4/9VuLic0X7K3tt36lzMF7TW2gAiJoMdfwZbogEeLly6HgRt8oqOh3l5JPxIqNU4Nb9G69m4e6udMNxkpgF3SU+bPsaUlhJqQ7FYeZCMB9G2A/WEAoFaCTXqSowbtF1zt7GVfdpI2oHdmXfZrbxnq85ilxMvS10twK4lqYEbDwu4PYXeTJWsrLdQzvf6JSmIGqfq/AHVkXYMqH1Drz44d9FP3LBvSTEaiuENYD8UPl0J9QWGJI86/TlL5rt+AKAXknm7QVCkYcGVgJKBSnZxLE24bIwjnda298wbPxeyDaXMJ0+7hNHummHTqF1LhFY8ezingWjE/37QS/i/EVvJcshXmL2QDEURHDnvYHVrbuYqPUimX3z+uTQsGbV2oKPfVV79XcebygVU2r9xIbAcms
  template:
    metadata:
      name: rabbitmq
      namespace: outegro
    type: Opaque
