apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-webhook
  namespace: outegro
spec:
  encryptedData:
    TELEGRAM_WEBHOOK_SECRET: AgCORjJuQ6DjsQNVjs2RVAuh+wUt1WI2EbxpYy9gwVStXAD+aabXqO1nFXxne8HFcpMLWuoW89kOOKZdibfEJbzVLk7UB7RttMTMqPpfxLRejaTA0zya0EEwaRLcFX/YiupLyOzey/fZv7QkV7tiwh8FHQdReXzLaCw4YbO1qTPTR0XiaaXf9CRA6dy9HTT/ar7Eq4vLiIrcKe2FdQ+TtInEvlu5XOUlNmc2krL4TbpBlEU0jPeoMBQTWbdtGsyWnfqrytxrofi4Nuq7CbS1P73omb3gtoCtSbMrZ8yR0tzhl+ic6EJb0+yUe+Po6m5tU0zwzVEdQjZQ7vY0g1fpDDHWWXNjW1cGscWbqepV2OTp6+XEId9oAOtS9S6dPFw7yP/NHJkobbwznJyTzWTjgSjgmhWqMhMb35rc2vX67ShmttSwnqBeLqjTnJ7syef7XKZyYzTdVrFQLOnnlaupJ9QKWSlhYOP9wQTQP+v692a5eVmAmLl/4gwF40dvTpKJEpzdJK16UsmW/MffPKPTJV0zDG7UE/MKvvbjmGD7lC/4Drl2ayszmm7K+1Jf3fXKMkfVe5Osw+hNPAOoQsTcByWpeZlGDY+KlbXosIyd2ZsYBf084XAuz+dXsQ63N3IVndcuMbvn835LU3fxjXH5W4o7uEe8O5L3uB59bK3sNyRvLHpI7P3KCa6wVayO0bpA04owVuFex2VPKRYvh91Xfhhu2SOFFmn2TRrHFMMDXN+wK+vZvewcz/8/6dgN8dTK3+2xkIFVmvqY6VB1AQhWbobb
  template:
    metadata:
      name: telegram-webhook
      namespace: outegro
    type: Opaque
