apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey
  namespace: outegro
spec:
  encryptedData:
    password: AgCPNsTYUfvsY2Man2nAzkbZxk/DfGfbEA9zDHcX5n/5LPwKEtdIp+t0E6nslucBtJ3LJYlOjYqCSxA3PlRs8qaiDL3HXtq3ie9Ckgxvf7LkXyQqMYdjgLiuH8T97x6HeUpgUDU9GakM8lyyIKTd3MaRQ6PHyueQMBFqf2uUXqxWso/sCXN+tDi8CB6ZNbHBvzhygH88RprrXSfPZpspJEcEoVxqOfUDlbUB+3T2v9Xz6n/wVjzlqF8239D6xrBeDlFf+f1BGZt1gkKayPD0uPbXL1hQAHP3BJllQRW0vxdvXdbxpgiGx/LinScSJwQCBfUTvrxjkS2XZ3X/eP+rH5HzxS5v+sqxLXwNL/5aYMaUVtBtIiCmD68nqtmloLJreWRpdvtfhDE/5o3GKOWGPXmvofnuWQJ3kb9e/DzOf8BXpx0Oki97RpwFoRRpiYV+mIQN+1gkZBxkGrw+TTUDMQQCkmG0p/CkJkdmVWAVbRN7tFZSEu6W1R11XLP6ZDXRpXeUguFaYII786gs+bIhRKmjbbiCxTi1gimVHXhqUQTNjT1LShL0WGhb5WfjXfSkTK+W1PBNzU/Khf639L2Hof+mdGEQNIW/w9dihUClNsJz6KP9RpUMfOxWFzZJVQcBYDVmyBkayCPh2qPab1+mkOz//n3ddoH+5ZD3rIg/E8qH2jz012f9fD0xdPNvU9P6rQMa6iMZymNNgjqzPCLbHqbcof6w/ftv419lnw0JyySR/a+JUd5uFwjzfdXQx2oq07KTO0zGOcqogAW4hvzNAPV/
  template:
    metadata:
      name: valkey
      namespace: outegro
    type: Opaque
